const assert = require("node:assert/strict"); const { test } = require("node:test");
const { planHourBatches, applyOnlyMissing, checkpointCursor, pendingAfterCursor, isCurrentCursor } = require("../scripts/scoped-backfill-batches");
const fs = require("node:fs"); const path = require("node:path");
test("resume batches only entries after a partial checkpoint and cap point writes", () => { const entries=Array.from({length:455},(_,i)=>({stableId:`p${i}`,pointCount:1,measuredAtMs:Date.parse("2026-09-15T01:00:00Z"),packetId:`${i}`})); const batches=planHourBatches(entries); assert.deepEqual(batches.map(b=>b.pointCount),[400,55]); });
test("batch idempotency excludes existing stable ids before rollup calculation", () => { const candidates=[{stableId:"a"},{stableId:"b"}]; assert.deepEqual(applyOnlyMissing(new Set(["a"]),candidates),[{stableId:"b"}]); assert.deepEqual(applyOnlyMissing(new Set(["a","b"]),candidates),[]); });
test("hour/stable-id cursor resumes despite unordered packet ids", () => { const b=planHourBatches([{packetId:"z",stableId:"b",pointCount:1,measuredAtMs:0},{packetId:"a",stableId:"a",pointCount:1,measuredAtMs:0},{packetId:"x",stableId:"c",pointCount:1,measuredAtMs:3600000}]); assert.equal(pendingAfterCursor(b,{utcHourMs:0,batchLastStableMeasurementId:"a"}).flatMap(x=>x.entries).length,2); });
test("crash then resume equals a clean run and legacy packet-id cursor is stale", () => { const entries=Array.from({length:6},(_,i)=>({packetId:["z","a","q","b","x","c"][i],stableId:`s${i}`,pointCount:1,measuredAtMs:i<3?0:3600000})); const all=planHourBatches(entries); const completed=all[0].entries.map(e=>e.stableId); const resumed=pendingAfterCursor(all,checkpointCursor(all[0])).flatMap(b=>b.entries).map(e=>e.stableId); assert.deepEqual([...completed,...resumed],entries.map(e=>e.stableId)); assert.equal(isCurrentCursor({lastCompletedPacketId:"z"}),false); });
test("checkpoint boundary excludes checkpoint point and retains its immediate successor", () => { const entries=["a","b","c","d"].map((stableId,index)=>({stableId,packetId:`unordered-${3-index}`,pointCount:1,measuredAtMs:0})); const batches=planHourBatches(entries); const afterLast=pendingAfterCursor(batches,{utcHourMs:0,batchLastStableMeasurementId:"d"}); assert.equal(afterLast.length,0); const afterMiddle=pendingAfterCursor(batches,{utcHourMs:0,batchLastStableMeasurementId:"b"}).flatMap(b=>b.entries).map(e=>e.stableId); assert.deepEqual(afterMiddle,["c","d"]); });
test("scoped executor and ingest use canonical rollups collection", () => { const scoped=fs.readFileSync(path.join(__dirname,"../scripts/backfill-monitoring-read-model-scoped.js"),"utf8"); const ingest=fs.readFileSync(path.join(__dirname,"../src/telemetry.ts"),"utf8"); assert.match(scoped,/\$\{root\}\/rollups\//); assert.doesNotMatch(scoped,/hourRollups/); assert.match(ingest,/monitoringTelemetry\/\$\{packet\.deviceId\}\/rollups\//); });
